### ISSUE TITLE
Company - POST - A client with valid token cannot create a company

### ISSUE THREAD

**Issue by sulenchy** [NoroffFEU/agency-api.noroff.dev#118] opened 2024-01-15 08:53 UTC
A client cannot create a company. How to recreate:

- log in as a client and get the token
Payload
```
{
  "firstName": "Client",
  "lastName": "test",
  "email": "abiodun.abudu+agency+client+test@noroff.no",
  "password": "**********",
  "role": "Client"
}
```
- create a company:
Token  `bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNjI0MGEyMi1hMWEwLTQ2NmItOGIxZS00ZmVmMTNlOWZiMGEiLCJlbWFpbCI6ImFiaW9kdW4uYWJ1ZHUrYWdlbmN5K2NsaWVudCt0ZXN0QG5vcm9mZi5ubyIsImlhdCI6MTcwNTMwODQ4MiwiZXhwIjoxNzA1Mzk0ODgyfQ.nbgJLwtvMDwKUbf8onC0SLftv6-sfspySjQSvsCq318`
`
Payload
```
{
  "name": "Tech Agency Inc",
  "sector": "Web Development.",
  "phone": 242424242424,
  "logo": "www.tech-agency-inc.com/logo.jpg",
  "admin": "a6240a22-a1a0-466b-8b1e-4fef13e9fb0a"
}
```

- Response from the server

```
{
    "message": "Invalid authorization token provided, please re-log."
}
```

- Suggestion
I think something is wrong in `verifyToken`

**Comment by chalund** [comment] 2024-01-15 10:19
@chrisbekk can you make this issue a top priority? Team Kolsås needs it sorted out to get started on their work.

**Comment by KarenJoo** [comment] 2024-01-15 11:24
@chalund Can confirm that this issue is assigned and prioritized

**Comment by runeunhjem** [comment] 2024-01-15 12:49
Actually made a company - needed to make the phonenumber a string:

{
  "name": "Holmenkollen Devs",
  "sector": "Listings.",
  "phone": "+47 12345678",
  "logo": "https://www.svgrepo.com/show/448058/logo.svg",
  "admin": "1345d9c4-6ceb-40a7-b1d0-32ab3de7033e"
}

This worked.

**Comment by kimrm** [comment] 2024-01-15 13:06
`{
  "name": "Tech Agency Inc",
  "sector": "Web Development.",
  "phone": "+47 12345345",
  "logo": "www.tech-agency-inc.com/logo.jpg",
  "admin": "804513e4-f68a-4697-861c-15bf694eb4d9"
}`

Response:
`{"message":"Only clients can create listings."}`

In company/middleware/checkAuth.js (backend) it seems this code kicks in:
`//Check user is allowed to create listings
    if (verified.role === "Applicant") {
      return res
        .status(401)
        .json({ message: "Only clients can create listings." });
    }`
    
    How can we change role for the user?

**Comment by chrisbekk** [comment] 2024-01-15 13:12
Will get to work on this issue ASAP. Need to setup some dependencies first.

**Comment by runeunhjem** [comment] 2024-01-15 13:14
Also i got the Create new listing to work -- was my bad - used wrong id.

**Comment by kimrm** [comment] 2024-01-15 13:25
> You can create a client user using your postman. See example below:
> 
> Url
> 
> https://agency-api.noroff.dev/users
> 
> Payload
> 
> { "firstName": "Client", "lastName": "test", "email": "[abiodun.abudu+agency+client+test@noroff.no](mailto:abiodun.abudu+agency+client+test@noroff.no)", "password": "Password123", "role": "Client" }

But this is logging in with Abi's user? How will a user who has signed up be able to create a company when they get the Applicant role as default?

The way this is structured in the backend it looks like companies are supposed to be created only by admin users.

In company/controllers/createCompany.js there is a check for Admin role:
```
if (admin !== user.id && user.role !== "Admin") {
    return res
      .status(400)
      .send({ message: "User's Id doesn't match request admin Id." });
  }
```

**Comment by Anclagen** [comment] 2024-01-15 13:30
Is this error using the main branch or the dev branch which will be more up to date in terms of code?

**Comment by runeunhjem** [comment] 2024-01-15 13:33
I have been using only main today, but seems all is working now tho

**Comment by runeunhjem** [comment] 2024-01-15 13:35
You can use any mail address and any name - point is to set the role as "Client" to be able to do the company stuff at least - The admin is another matter - I havnt touched that yet. @kimrm

**Comment by kimrm** [comment] 2024-01-15 13:40
Ah. So when logging in, the frontend can decide the role for the user. That's a bit weird, but okay :)

**Comment by runeunhjem** [comment] 2024-01-15 13:42
I am only using postman - Have not been able to log in with a client account @kimrm

**Comment by kimrm** [comment] 2024-01-15 13:47
> I am only using postman - Have not been able to log in with a client account @kimrm

Sorry, I misunderstood. My bad. I didn't know the role could be set when registering the user. This should be in the swagger docs.

**Comment by sulenchy** [comment] 2024-01-15 14:17
@runeunhjem Can you share the working payload for Company POST?

**Comment by runeunhjem** [comment] 2024-01-15 14:20
```
{
  "name": "Holmenkollen Devs",
  "sector": "Listings.",
  "phone": "+47 12345678",
  "logo": "https://www.svgrepo.com/show/448058/logo.svg",
  "admin": "1345d9c4-6ceb-40a7-b1d0-32ab3de7033e"
}
```
admin is the Client ID

@sulenchy

**Comment by kimrm** [comment] 2024-01-16 10:57
What's the status here? Will this be kept as it is, or will there be some changes to how a company is created? We are waiting to make some changes to the registration form.

@NoroffFEU/grefsenkollen

**Comment by Anclagen** [comment] 2024-01-16 12:25
I have had no problems creating a client user and company on the main or dev branches when trying to reproduce this error. 

![Screenshot 2024-01-16 131025](https://github.com/NoroffFEU/agency-api.noroff.dev/assets/91462616/f6cfaf52-bc47-4fc5-ac16-ff9dd80d6fd1)

I also have a company setup currently running version of the API too.
![Screenshot 2024-01-16 131731](https://github.com/NoroffFEU/agency-api.noroff.dev/assets/91462616/d32b104d-faa1-4794-bcac-140368c38a10)

Some thing to note while trying to reproduce this:
- We should remove the `admin` requirement from the payload as we can get the user id ourselves with the verification token.
- If you create a second company with the same user the old company remains and you are removed as admin, leaving companies without admins so a check for existing company is required, or an update to the schema to allow a client to have multiple companies.

**Comment by RamtinMoshtagh** [comment] 2024-01-16 14:01
There was another one on this and he asked for someone else to look at it, so i have assigned myself to it. Will give it a look now @kimrm @Anclagen 

Based on the comments, it looks like something is working, but ofc needs adjustments.

**Comment by Anclagen** [comment] 2024-01-18 19:16
As people are able to create companies I will close this issue as it has spawned various issue that appear to have caused the problem in the first place.

**Closed by Anclagen** 2024-01-18 19:16 UTC
Labels: bug
